{% set name = "ghostPii" %}
{% set version = "1.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ghostPii-{{ version }}.tar.gz
  sha256: d215dd70be84f4a48d720436ef59dd5a255407ae06f449996ab3fca771d0c08b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - setuptools >=42
    - pip
    - python >=3.6
  run:
    - IPython
    - numpy
    - pandas
    - python >=3.6
    - requests
    - scipy
    - sqlalchemy
    - sympy

test:
  imports:
    - ghostPii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/capnion/ghostpii_client
  summary: A homomorphic encryption package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackp97
    - BirdMueller
